services:
  - type: web
    name: euro-denomination-backend
    env: docker
    dockerfilePath: ./backend-deploy/Dockerfile
    plan: free

  - type: web
    name: euro-denomination-frontend
    env: docker
    dockerfilePath: ./frontend-deploy/Dockerfile
    plan: free
